//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace CarService
{
    using System;
    [DataContract]
    public enum StareComanda : byte
    {
        [EnumMember]
        InAsteptare = 1,
        [EnumMember]
        Executata = 2,
        [EnumMember]
        Refuzata = 3,
        [EnumMember]
        Necunoscuta = 0
    }
}
