//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mecanic
    {
        public int Id { get; private set; }
        public string Nume { get; private set; }
        public string Prenume { get; private set; }
        public int DetaliuComandaId { get; set; }
    
        public virtual DetaliuComanda DetaliuComanda { get; set; }
    }
}
