//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceProject
{
    using System;
    
    public enum StareComanda : byte
    {
        ASTEPTARE = 1,
        EXECUTATA = 2,
        REFUZATA = 3
    }
}
