//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AdresaField;
        
        private CarService.Auto[] AutomobileField;
        
        private string EmailField;
        
        private int IdField;
        
        private string JudetField;
        
        private string LocalitateField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        private string TelefonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa
        {
            get
            {
                return this.AdresaField;
            }
            set
            {
                this.AdresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Auto[] Automobile
        {
            get
            {
                return this.AutomobileField;
            }
            set
            {
                this.AutomobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Judet
        {
            get
            {
                return this.JudetField;
            }
            set
            {
                this.JudetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localitate
        {
            get
            {
                return this.LocalitateField;
            }
            set
            {
                this.LocalitateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auto", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Auto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarService.Client ClientField;
        
        private int ClientIdField;
        
        private CarService.Comanda[] ComenziField;
        
        private int IdField;
        
        private string NumarAutoField;
        
        private CarService.Sasiu SasiuField;
        
        private int SasiuIdField;
        
        private string SerieSasiuField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Client Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Comanda[] Comenzi
        {
            get
            {
                return this.ComenziField;
            }
            set
            {
                this.ComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumarAuto
        {
            get
            {
                return this.NumarAutoField;
            }
            set
            {
                this.NumarAutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Sasiu Sasiu
        {
            get
            {
                return this.SasiuField;
            }
            set
            {
                this.SasiuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SasiuId
        {
            get
            {
                return this.SasiuIdField;
            }
            set
            {
                this.SasiuIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieSasiu
        {
            get
            {
                return this.SerieSasiuField;
            }
            set
            {
                this.SerieSasiuField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sasiu", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Sasiu : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarService.Auto[] AutomobileField;
        
        private string CodSasiuField;
        
        private string DenumireField;
        
        private int IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Auto[] Automobile
        {
            get
            {
                return this.AutomobileField;
            }
            set
            {
                this.AutomobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodSasiu
        {
            get
            {
                return this.CodSasiuField;
            }
            set
            {
                this.CodSasiuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comanda", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Comanda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarService.Auto AutoField;
        
        private int AutoIdField;
        
        private System.DateTime DataFinalizareField;
        
        private System.DateTime DataProgramareField;
        
        private System.DateTime DataSystemField;
        
        private string DescriereField;
        
        private CarService.DetaliuComanda[] DetaliiComenziField;
        
        private int IdField;
        
        private int KmBordField;
        
        private CarService.StareComanda StareComandaField;
        
        private decimal ValoarePieseField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Auto Auto
        {
            get
            {
                return this.AutoField;
            }
            set
            {
                this.AutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutoId
        {
            get
            {
                return this.AutoIdField;
            }
            set
            {
                this.AutoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataFinalizare
        {
            get
            {
                return this.DataFinalizareField;
            }
            set
            {
                this.DataFinalizareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataProgramare
        {
            get
            {
                return this.DataProgramareField;
            }
            set
            {
                this.DataProgramareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataSystem
        {
            get
            {
                return this.DataSystemField;
            }
            set
            {
                this.DataSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.DetaliuComanda[] DetaliiComenzi
        {
            get
            {
                return this.DetaliiComenziField;
            }
            set
            {
                this.DetaliiComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KmBord
        {
            get
            {
                return this.KmBordField;
            }
            set
            {
                this.KmBordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.StareComanda StareComanda
        {
            get
            {
                return this.StareComandaField;
            }
            set
            {
                this.StareComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValoarePiese
        {
            get
            {
                return this.ValoarePieseField;
            }
            set
            {
                this.ValoarePieseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetaliuComanda", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class DetaliuComanda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarService.Comanda ComandaField;
        
        private int ComandaIdField;
        
        private int IdField;
        
        private CarService.Imagine[] ImaginiField;
        
        private CarService.Material[] MaterialeField;
        
        private CarService.Mecanic[] MecaniciField;
        
        private CarService.Operatie[] OperatiiField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Comanda Comanda
        {
            get
            {
                return this.ComandaField;
            }
            set
            {
                this.ComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComandaId
        {
            get
            {
                return this.ComandaIdField;
            }
            set
            {
                this.ComandaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Imagine[] Imagini
        {
            get
            {
                return this.ImaginiField;
            }
            set
            {
                this.ImaginiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Material[] Materiale
        {
            get
            {
                return this.MaterialeField;
            }
            set
            {
                this.MaterialeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Mecanic[] Mecanici
        {
            get
            {
                return this.MecaniciField;
            }
            set
            {
                this.MecaniciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Operatie[] Operatii
        {
            get
            {
                return this.OperatiiField;
            }
            set
            {
                this.OperatiiField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StareComanda", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public enum StareComanda : byte
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InAsteptare = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Executata = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refuzata = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Necunoscuta = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagine", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Imagine : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DataField;
        
        private string DescriereField;
        
        private CarService.DetaliuComanda[] DetaliiComenziField;
        
        private byte[] FotoField;
        
        private int IdField;
        
        private string TitluField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.DetaliuComanda[] DetaliiComenzi
        {
            get
            {
                return this.DetaliiComenziField;
            }
            set
            {
                this.DetaliiComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                this.FotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu
        {
            get
            {
                return this.TitluField;
            }
            set
            {
                this.TitluField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal CantitateField;
        
        private System.DateTime DataAprovizionareField;
        
        private string DenumireField;
        
        private CarService.DetaliuComanda[] DetaliiComenziField;
        
        private int IdField;
        
        private decimal PretField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantitate
        {
            get
            {
                return this.CantitateField;
            }
            set
            {
                this.CantitateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAprovizionare
        {
            get
            {
                return this.DataAprovizionareField;
            }
            set
            {
                this.DataAprovizionareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.DetaliuComanda[] DetaliiComenzi
        {
            get
            {
                return this.DetaliiComenziField;
            }
            set
            {
                this.DetaliiComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pret
        {
            get
            {
                return this.PretField;
            }
            set
            {
                this.PretField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mecanic", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Mecanic : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarService.DetaliuComanda[] DetaliiComenziField;
        
        private int IdField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.DetaliuComanda[] DetaliiComenzi
        {
            get
            {
                return this.DetaliiComenziField;
            }
            set
            {
                this.DetaliiComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operatie", Namespace="http://schemas.datacontract.org/2004/07/CarService")]
    public partial class Operatie : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DenumireField;
        
        private CarService.DetaliuComanda[] DetaliiComenziField;
        
        private int IdField;
        
        private decimal TimpExecutieField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.DetaliuComanda[] DetaliiComenzi
        {
            get
            {
                return this.DetaliiComenziField;
            }
            set
            {
                this.DetaliiComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TimpExecutie
        {
            get
            {
                return this.TimpExecutieField;
            }
            set
            {
                this.TimpExecutieField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICarService")]
public interface ICarService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindCustomer", ReplyAction="http://tempuri.org/ICarService/FindCustomerResponse")]
    CarService.Client FindCustomer(string nume, string prenume, string phoneNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindCustomer", ReplyAction="http://tempuri.org/ICarService/FindCustomerResponse")]
    System.Threading.Tasks.Task<CarService.Client> FindCustomerAsync(string nume, string prenume, string phoneNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddCustomer", ReplyAction="http://tempuri.org/ICarService/AddCustomerResponse")]
    void AddCustomer(CarService.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddCustomer", ReplyAction="http://tempuri.org/ICarService/AddCustomerResponse")]
    System.Threading.Tasks.Task AddCustomerAsync(CarService.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetAllCustomers", ReplyAction="http://tempuri.org/ICarService/GetAllCustomersResponse")]
    CarService.Client[] GetAllCustomers();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetAllCustomers", ReplyAction="http://tempuri.org/ICarService/GetAllCustomersResponse")]
    System.Threading.Tasks.Task<CarService.Client[]> GetAllCustomersAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddChassis", ReplyAction="http://tempuri.org/ICarService/AddChassisResponse")]
    void AddChassis(CarService.Sasiu sasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddChassis", ReplyAction="http://tempuri.org/ICarService/AddChassisResponse")]
    System.Threading.Tasks.Task AddChassisAsync(CarService.Sasiu sasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindChassisByCode", ReplyAction="http://tempuri.org/ICarService/FindChassisByCodeResponse")]
    CarService.Sasiu FindChassisByCode(string chassisCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindChassisByCode", ReplyAction="http://tempuri.org/ICarService/FindChassisByCodeResponse")]
    System.Threading.Tasks.Task<CarService.Sasiu> FindChassisByCodeAsync(string chassisCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddAuto", ReplyAction="http://tempuri.org/ICarService/AddAutoResponse")]
    void AddAuto(CarService.Auto auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddAuto", ReplyAction="http://tempuri.org/ICarService/AddAutoResponse")]
    System.Threading.Tasks.Task AddAutoAsync(CarService.Auto auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddMaterial", ReplyAction="http://tempuri.org/ICarService/AddMaterialResponse")]
    void AddMaterial(CarService.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddMaterial", ReplyAction="http://tempuri.org/ICarService/AddMaterialResponse")]
    System.Threading.Tasks.Task AddMaterialAsync(CarService.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddOrder", ReplyAction="http://tempuri.org/ICarService/AddOrderResponse")]
    void AddOrder(CarService.Comanda comanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddOrder", ReplyAction="http://tempuri.org/ICarService/AddOrderResponse")]
    System.Threading.Tasks.Task AddOrderAsync(CarService.Comanda comanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddOperation", ReplyAction="http://tempuri.org/ICarService/AddOperationResponse")]
    void AddOperation(CarService.Operatie operation);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddOperation", ReplyAction="http://tempuri.org/ICarService/AddOperationResponse")]
    System.Threading.Tasks.Task AddOperationAsync(CarService.Operatie operation);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddMecanic", ReplyAction="http://tempuri.org/ICarService/AddMecanicResponse")]
    void AddMecanic(CarService.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddMecanic", ReplyAction="http://tempuri.org/ICarService/AddMecanicResponse")]
    System.Threading.Tasks.Task AddMecanicAsync(CarService.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddImage", ReplyAction="http://tempuri.org/ICarService/AddImageResponse")]
    void AddImage(CarService.Imagine image);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddImage", ReplyAction="http://tempuri.org/ICarService/AddImageResponse")]
    System.Threading.Tasks.Task AddImageAsync(CarService.Imagine image);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateClient", ReplyAction="http://tempuri.org/ICarService/UpdateClientResponse")]
    void UpdateClient(CarService.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateClient", ReplyAction="http://tempuri.org/ICarService/UpdateClientResponse")]
    System.Threading.Tasks.Task UpdateClientAsync(CarService.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateOrder", ReplyAction="http://tempuri.org/ICarService/UpdateOrderResponse")]
    void UpdateOrder(CarService.Comanda order);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateOrder", ReplyAction="http://tempuri.org/ICarService/UpdateOrderResponse")]
    System.Threading.Tasks.Task UpdateOrderAsync(CarService.Comanda order);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindOrderById", ReplyAction="http://tempuri.org/ICarService/FindOrderByIdResponse")]
    CarService.Comanda FindOrderById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindOrderById", ReplyAction="http://tempuri.org/ICarService/FindOrderByIdResponse")]
    System.Threading.Tasks.Task<CarService.Comanda> FindOrderByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindCustomerById", ReplyAction="http://tempuri.org/ICarService/FindCustomerByIdResponse")]
    CarService.Client FindCustomerById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindCustomerById", ReplyAction="http://tempuri.org/ICarService/FindCustomerByIdResponse")]
    System.Threading.Tasks.Task<CarService.Client> FindCustomerByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteClient", ReplyAction="http://tempuri.org/ICarService/DeleteClientResponse")]
    void DeleteClient(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteClient", ReplyAction="http://tempuri.org/ICarService/DeleteClientResponse")]
    System.Threading.Tasks.Task DeleteClientAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/ExistsClient", ReplyAction="http://tempuri.org/ICarService/ExistsClientResponse")]
    bool ExistsClient(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/ExistsClient", ReplyAction="http://tempuri.org/ICarService/ExistsClientResponse")]
    System.Threading.Tasks.Task<bool> ExistsClientAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteOrder", ReplyAction="http://tempuri.org/ICarService/DeleteOrderResponse")]
    void DeleteOrder(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteOrder", ReplyAction="http://tempuri.org/ICarService/DeleteOrderResponse")]
    System.Threading.Tasks.Task DeleteOrderAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindMaterialById", ReplyAction="http://tempuri.org/ICarService/FindMaterialByIdResponse")]
    CarService.Material FindMaterialById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindMaterialById", ReplyAction="http://tempuri.org/ICarService/FindMaterialByIdResponse")]
    System.Threading.Tasks.Task<CarService.Material> FindMaterialByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindOperationById", ReplyAction="http://tempuri.org/ICarService/FindOperationByIdResponse")]
    CarService.Operatie FindOperationById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindOperationById", ReplyAction="http://tempuri.org/ICarService/FindOperationByIdResponse")]
    System.Threading.Tasks.Task<CarService.Operatie> FindOperationByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindMecanicById", ReplyAction="http://tempuri.org/ICarService/FindMecanicByIdResponse")]
    CarService.Mecanic FindMecanicById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindMecanicById", ReplyAction="http://tempuri.org/ICarService/FindMecanicByIdResponse")]
    System.Threading.Tasks.Task<CarService.Mecanic> FindMecanicByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindImageById", ReplyAction="http://tempuri.org/ICarService/FindImageByIdResponse")]
    CarService.Imagine FindImageById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindImageById", ReplyAction="http://tempuri.org/ICarService/FindImageByIdResponse")]
    System.Threading.Tasks.Task<CarService.Imagine> FindImageByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddOrderDetails", ReplyAction="http://tempuri.org/ICarService/AddOrderDetailsResponse")]
    void AddOrderDetails(CarService.DetaliuComanda orderDetails);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddOrderDetails", ReplyAction="http://tempuri.org/ICarService/AddOrderDetailsResponse")]
    System.Threading.Tasks.Task AddOrderDetailsAsync(CarService.DetaliuComanda orderDetails);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindChassisById", ReplyAction="http://tempuri.org/ICarService/FindChassisByIdResponse")]
    CarService.Sasiu FindChassisById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/FindChassisById", ReplyAction="http://tempuri.org/ICarService/FindChassisByIdResponse")]
    System.Threading.Tasks.Task<CarService.Sasiu> FindChassisByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateChassis", ReplyAction="http://tempuri.org/ICarService/UpdateChassisResponse")]
    void UpdateChassis(CarService.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateChassis", ReplyAction="http://tempuri.org/ICarService/UpdateChassisResponse")]
    System.Threading.Tasks.Task UpdateChassisAsync(CarService.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteChassis", ReplyAction="http://tempuri.org/ICarService/DeleteChassisResponse")]
    void DeleteChassis(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteChassis", ReplyAction="http://tempuri.org/ICarService/DeleteChassisResponse")]
    System.Threading.Tasks.Task DeleteChassisAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateMecanic", ReplyAction="http://tempuri.org/ICarService/UpdateMecanicResponse")]
    void UpdateMecanic(CarService.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateMecanic", ReplyAction="http://tempuri.org/ICarService/UpdateMecanicResponse")]
    System.Threading.Tasks.Task UpdateMecanicAsync(CarService.Mecanic mecanic);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteMecanic", ReplyAction="http://tempuri.org/ICarService/DeleteMecanicResponse")]
    void DeleteMecanic(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteMecanic", ReplyAction="http://tempuri.org/ICarService/DeleteMecanicResponse")]
    System.Threading.Tasks.Task DeleteMecanicAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateImage", ReplyAction="http://tempuri.org/ICarService/UpdateImageResponse")]
    void UpdateImage(CarService.Imagine image);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateImage", ReplyAction="http://tempuri.org/ICarService/UpdateImageResponse")]
    System.Threading.Tasks.Task UpdateImageAsync(CarService.Imagine image);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteImage", ReplyAction="http://tempuri.org/ICarService/DeleteImageResponse")]
    void DeleteImage(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteImage", ReplyAction="http://tempuri.org/ICarService/DeleteImageResponse")]
    System.Threading.Tasks.Task DeleteImageAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateMaterial", ReplyAction="http://tempuri.org/ICarService/UpdateMaterialResponse")]
    void UpdateMaterial(CarService.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateMaterial", ReplyAction="http://tempuri.org/ICarService/UpdateMaterialResponse")]
    System.Threading.Tasks.Task UpdateMaterialAsync(CarService.Material material);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteMaterial", ReplyAction="http://tempuri.org/ICarService/DeleteMaterialResponse")]
    void DeleteMaterial(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteMaterial", ReplyAction="http://tempuri.org/ICarService/DeleteMaterialResponse")]
    System.Threading.Tasks.Task DeleteMaterialAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateOperation", ReplyAction="http://tempuri.org/ICarService/UpdateOperationResponse")]
    void UpdateOperation(CarService.Operatie operation);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateOperation", ReplyAction="http://tempuri.org/ICarService/UpdateOperationResponse")]
    System.Threading.Tasks.Task UpdateOperationAsync(CarService.Operatie operation);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteOperation", ReplyAction="http://tempuri.org/ICarService/DeleteOperationResponse")]
    void DeleteOperation(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteOperation", ReplyAction="http://tempuri.org/ICarService/DeleteOperationResponse")]
    System.Threading.Tasks.Task DeleteOperationAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/ExistsCustomer", ReplyAction="http://tempuri.org/ICarService/ExistsCustomerResponse")]
    bool ExistsCustomer(string email);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/ExistsCustomer", ReplyAction="http://tempuri.org/ICarService/ExistsCustomerResponse")]
    System.Threading.Tasks.Task<bool> ExistsCustomerAsync(string email);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICarServiceChannel : ICarService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CarServiceClient : System.ServiceModel.ClientBase<ICarService>, ICarService
{
    
    public CarServiceClient()
    {
    }
    
    public CarServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CarServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public CarService.Client FindCustomer(string nume, string prenume, string phoneNumber)
    {
        return base.Channel.FindCustomer(nume, prenume, phoneNumber);
    }
    
    public System.Threading.Tasks.Task<CarService.Client> FindCustomerAsync(string nume, string prenume, string phoneNumber)
    {
        return base.Channel.FindCustomerAsync(nume, prenume, phoneNumber);
    }
    
    public void AddCustomer(CarService.Client client)
    {
        base.Channel.AddCustomer(client);
    }
    
    public System.Threading.Tasks.Task AddCustomerAsync(CarService.Client client)
    {
        return base.Channel.AddCustomerAsync(client);
    }
    
    public CarService.Client[] GetAllCustomers()
    {
        return base.Channel.GetAllCustomers();
    }
    
    public System.Threading.Tasks.Task<CarService.Client[]> GetAllCustomersAsync()
    {
        return base.Channel.GetAllCustomersAsync();
    }
    
    public void AddChassis(CarService.Sasiu sasiu)
    {
        base.Channel.AddChassis(sasiu);
    }
    
    public System.Threading.Tasks.Task AddChassisAsync(CarService.Sasiu sasiu)
    {
        return base.Channel.AddChassisAsync(sasiu);
    }
    
    public CarService.Sasiu FindChassisByCode(string chassisCode)
    {
        return base.Channel.FindChassisByCode(chassisCode);
    }
    
    public System.Threading.Tasks.Task<CarService.Sasiu> FindChassisByCodeAsync(string chassisCode)
    {
        return base.Channel.FindChassisByCodeAsync(chassisCode);
    }
    
    public void AddAuto(CarService.Auto auto)
    {
        base.Channel.AddAuto(auto);
    }
    
    public System.Threading.Tasks.Task AddAutoAsync(CarService.Auto auto)
    {
        return base.Channel.AddAutoAsync(auto);
    }
    
    public void AddMaterial(CarService.Material material)
    {
        base.Channel.AddMaterial(material);
    }
    
    public System.Threading.Tasks.Task AddMaterialAsync(CarService.Material material)
    {
        return base.Channel.AddMaterialAsync(material);
    }
    
    public void AddOrder(CarService.Comanda comanda)
    {
        base.Channel.AddOrder(comanda);
    }
    
    public System.Threading.Tasks.Task AddOrderAsync(CarService.Comanda comanda)
    {
        return base.Channel.AddOrderAsync(comanda);
    }
    
    public void AddOperation(CarService.Operatie operation)
    {
        base.Channel.AddOperation(operation);
    }
    
    public System.Threading.Tasks.Task AddOperationAsync(CarService.Operatie operation)
    {
        return base.Channel.AddOperationAsync(operation);
    }
    
    public void AddMecanic(CarService.Mecanic mecanic)
    {
        base.Channel.AddMecanic(mecanic);
    }
    
    public System.Threading.Tasks.Task AddMecanicAsync(CarService.Mecanic mecanic)
    {
        return base.Channel.AddMecanicAsync(mecanic);
    }
    
    public void AddImage(CarService.Imagine image)
    {
        base.Channel.AddImage(image);
    }
    
    public System.Threading.Tasks.Task AddImageAsync(CarService.Imagine image)
    {
        return base.Channel.AddImageAsync(image);
    }
    
    public void UpdateClient(CarService.Client client)
    {
        base.Channel.UpdateClient(client);
    }
    
    public System.Threading.Tasks.Task UpdateClientAsync(CarService.Client client)
    {
        return base.Channel.UpdateClientAsync(client);
    }
    
    public void UpdateOrder(CarService.Comanda order)
    {
        base.Channel.UpdateOrder(order);
    }
    
    public System.Threading.Tasks.Task UpdateOrderAsync(CarService.Comanda order)
    {
        return base.Channel.UpdateOrderAsync(order);
    }
    
    public CarService.Comanda FindOrderById(int id)
    {
        return base.Channel.FindOrderById(id);
    }
    
    public System.Threading.Tasks.Task<CarService.Comanda> FindOrderByIdAsync(int id)
    {
        return base.Channel.FindOrderByIdAsync(id);
    }
    
    public CarService.Client FindCustomerById(int id)
    {
        return base.Channel.FindCustomerById(id);
    }
    
    public System.Threading.Tasks.Task<CarService.Client> FindCustomerByIdAsync(int id)
    {
        return base.Channel.FindCustomerByIdAsync(id);
    }
    
    public void DeleteClient(int id)
    {
        base.Channel.DeleteClient(id);
    }
    
    public System.Threading.Tasks.Task DeleteClientAsync(int id)
    {
        return base.Channel.DeleteClientAsync(id);
    }
    
    public bool ExistsClient(int id)
    {
        return base.Channel.ExistsClient(id);
    }
    
    public System.Threading.Tasks.Task<bool> ExistsClientAsync(int id)
    {
        return base.Channel.ExistsClientAsync(id);
    }
    
    public void DeleteOrder(int id)
    {
        base.Channel.DeleteOrder(id);
    }
    
    public System.Threading.Tasks.Task DeleteOrderAsync(int id)
    {
        return base.Channel.DeleteOrderAsync(id);
    }
    
    public CarService.Material FindMaterialById(int id)
    {
        return base.Channel.FindMaterialById(id);
    }
    
    public System.Threading.Tasks.Task<CarService.Material> FindMaterialByIdAsync(int id)
    {
        return base.Channel.FindMaterialByIdAsync(id);
    }
    
    public CarService.Operatie FindOperationById(int id)
    {
        return base.Channel.FindOperationById(id);
    }
    
    public System.Threading.Tasks.Task<CarService.Operatie> FindOperationByIdAsync(int id)
    {
        return base.Channel.FindOperationByIdAsync(id);
    }
    
    public CarService.Mecanic FindMecanicById(int id)
    {
        return base.Channel.FindMecanicById(id);
    }
    
    public System.Threading.Tasks.Task<CarService.Mecanic> FindMecanicByIdAsync(int id)
    {
        return base.Channel.FindMecanicByIdAsync(id);
    }
    
    public CarService.Imagine FindImageById(int id)
    {
        return base.Channel.FindImageById(id);
    }
    
    public System.Threading.Tasks.Task<CarService.Imagine> FindImageByIdAsync(int id)
    {
        return base.Channel.FindImageByIdAsync(id);
    }
    
    public void AddOrderDetails(CarService.DetaliuComanda orderDetails)
    {
        base.Channel.AddOrderDetails(orderDetails);
    }
    
    public System.Threading.Tasks.Task AddOrderDetailsAsync(CarService.DetaliuComanda orderDetails)
    {
        return base.Channel.AddOrderDetailsAsync(orderDetails);
    }
    
    public CarService.Sasiu FindChassisById(int id)
    {
        return base.Channel.FindChassisById(id);
    }
    
    public System.Threading.Tasks.Task<CarService.Sasiu> FindChassisByIdAsync(int id)
    {
        return base.Channel.FindChassisByIdAsync(id);
    }
    
    public void UpdateChassis(CarService.Sasiu chassis)
    {
        base.Channel.UpdateChassis(chassis);
    }
    
    public System.Threading.Tasks.Task UpdateChassisAsync(CarService.Sasiu chassis)
    {
        return base.Channel.UpdateChassisAsync(chassis);
    }
    
    public void DeleteChassis(int id)
    {
        base.Channel.DeleteChassis(id);
    }
    
    public System.Threading.Tasks.Task DeleteChassisAsync(int id)
    {
        return base.Channel.DeleteChassisAsync(id);
    }
    
    public void UpdateMecanic(CarService.Mecanic mecanic)
    {
        base.Channel.UpdateMecanic(mecanic);
    }
    
    public System.Threading.Tasks.Task UpdateMecanicAsync(CarService.Mecanic mecanic)
    {
        return base.Channel.UpdateMecanicAsync(mecanic);
    }
    
    public void DeleteMecanic(int id)
    {
        base.Channel.DeleteMecanic(id);
    }
    
    public System.Threading.Tasks.Task DeleteMecanicAsync(int id)
    {
        return base.Channel.DeleteMecanicAsync(id);
    }
    
    public void UpdateImage(CarService.Imagine image)
    {
        base.Channel.UpdateImage(image);
    }
    
    public System.Threading.Tasks.Task UpdateImageAsync(CarService.Imagine image)
    {
        return base.Channel.UpdateImageAsync(image);
    }
    
    public void DeleteImage(int id)
    {
        base.Channel.DeleteImage(id);
    }
    
    public System.Threading.Tasks.Task DeleteImageAsync(int id)
    {
        return base.Channel.DeleteImageAsync(id);
    }
    
    public void UpdateMaterial(CarService.Material material)
    {
        base.Channel.UpdateMaterial(material);
    }
    
    public System.Threading.Tasks.Task UpdateMaterialAsync(CarService.Material material)
    {
        return base.Channel.UpdateMaterialAsync(material);
    }
    
    public void DeleteMaterial(int id)
    {
        base.Channel.DeleteMaterial(id);
    }
    
    public System.Threading.Tasks.Task DeleteMaterialAsync(int id)
    {
        return base.Channel.DeleteMaterialAsync(id);
    }
    
    public void UpdateOperation(CarService.Operatie operation)
    {
        base.Channel.UpdateOperation(operation);
    }
    
    public System.Threading.Tasks.Task UpdateOperationAsync(CarService.Operatie operation)
    {
        return base.Channel.UpdateOperationAsync(operation);
    }
    
    public void DeleteOperation(int id)
    {
        base.Channel.DeleteOperation(id);
    }
    
    public System.Threading.Tasks.Task DeleteOperationAsync(int id)
    {
        return base.Channel.DeleteOperationAsync(id);
    }
    
    public bool ExistsCustomer(string email)
    {
        return base.Channel.ExistsCustomer(email);
    }
    
    public System.Threading.Tasks.Task<bool> ExistsCustomerAsync(string email)
    {
        return base.Channel.ExistsCustomerAsync(email);
    }
}
